name = "§l§9NEWB §fx §9GEMINI§r"
version = [0, 1, 0]
min_supported_mc_version = [1, 21, 20]
description = '''
§7Make your Minecraft with vibrant, dynamic lighting and an immersive atmosphere§r
§c%w - %v
''' # %w = patch warning, %v = version
authors = ["firmw4", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "612cd0f1-2481-442b-a390-2e927ee66985" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Weather", "Actor"]

[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
''' # %a = authors
credits = '''
'''

[custom]
label = '''
§7Another variant to improve your Minecraft visual, dynamic lighting and immersive atmosphere. This variant uses visual inspiration and coloring from AI

§fThese are some things you should do:
- Set brightness to 0-30
- Set render distance to 8-12 to get better fog (short render distance = more fog)
- Disable vsync for better performance
- Don't use experimental feature and/or education edtion

To find out about shader changes and updates, visit Newb Community discord server:
https://discord.gg/newb-community-844591537430069279
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default


[[subpack]]
define = "SOFT_CLOUDS"
materials = ["Clouds"]
description = '''
Soft Clouds
'''

[[subpack]]
define = "BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
Box Clouds
'''

[[subpack]]
define = "ALWAYS_REFLECTION"
materials = ["RenderChunk"]
description = '''
Always ground reflection
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No wave effects
'''

[[subpack]]
define = "LT_BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
lite box
'''

[[subpack]]
define = "LT_SOFT_CLOUDS"
materials = ["RenderChunk"]
description = '''
lite soft
'''

[[subpack]]
define = "LT_AR"
materials = ["RenderChunk"]
description = '''
lite ar
'''

[[subpack]]
define = "LITE"
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Weather", "Actor"]
description = '''
lite
'''

[[subpack]]
define = "UL_BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
ultra box
'''

[[subpack]]
define = "UL_SOFT_CLOUDS"
materials = ["Clouds"]
description = '''
ultra soft
'''

[[subpack]]
define = "UL_AR"
materials = ["RenderChunk"]
description = '''
ultra ar
'''

[[subpack]]
define = "ULTRA"
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Weather", "Actor"]
description = '''
ultra
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
