name = "§lNewb X §6Pineapple§r"
version = [0, 2, 0]
url = "https://firmw4.vercel.app/"
authors = ["devendrn", "firmw4"]
min_supported_mc_version = [1, 20, 80]
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Actor"]

[description]
# %w = patch warning, %v = version
long = '''
§7An aesthetic shader with a chill color theme§r
%v
§c%w
'''
short = "Legacy port of Newb Shader for RenderDragon"

[uuid] # Use https://www.uuidgenerator.net/version4
header = "12d4ea4a-7439-4969-b936-9ad0d511d7d1"
module = "8e745b9f-ec80-45c1-bdc3-578ab7cbd4b6"

[info]
# %a = authors
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
'''
credits = '''
devendrn, firmw4
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default


[[subpack]]
define = "VOLUMETRIC_CLOUDS"
materials = ["Clouds"]
description = '''
§4Volumetric Clouds§r

Summary: Realistic volumetric clouds style
§cImportant! Some types of GPU do not support this clouds style§r
'''

[[subpack]]
define = "MULTILAYER_CLOUDS"
materials = ["Clouds"]
description = '''
§9Multilayer Clouds§r

Summary: Add more clouds layer
'''

[[subpack]]
define = "SIMPLE_CLOUDS"
materials = ["Clouds"]
description = '''
§3Simple Clouds§r

Summary: Change to simple clouds style
'''

[[subpack]]
define = "VANILLA_CLOUDS"
materials = ["Clouds"]
description = '''
§6Vanilla Clouds§r

Summary: Change to vanilla clouds style
'''

[[subpack]]
define = "ALWAYS_REFLECTION"
materials = ["RenderChunk"]
description = '''
§eAlways Reflection§r

Summary: Enable aurora and ground reflection effect
'''

[[subpack]]
define = "RAINBOWS"
materials = ["Sky"]
description = '''
§4R§6a§ei§an§2b§1o§5w§ds§r

Summary: Show rainbow effect on sky
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
§aNo Wave§r

Summary: No wave effect
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default

Summary: Rounded clouds, wave effect and aurora at night
'''
