name = "§lNewb X §6Pineapple§r"
version = [0, 1, 0]
url = "https://firmw4.vercel.app/minecraft-shader/"
authors = ["firmw4"]
min_supported_mc_version = [1, 20, 80]
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Actor"]

[description]
# %w = patch warning, %v = version
long = '''
§7An aesthetic shader with a chill color theme §r%v
§c%w
'''
short = "An aesthetic shader with a chill color theme"

[uuid] # Use https://www.uuidgenerator.net/version4
header = "e65a32bc-b0aa-4ac0-9d5c-f4f8ba62c3aa"
module = "fecd06fa-2960-46af-9fa9-bd0ff8a34c5e"

# subpacks are arranged in left to right order
# right-most subpack is enabled by default


[[subpack]]
define = "RAINBOWS"
materials = ["Sky"]
description = '''
§4R§6a§ei§an§2b§1o§5w§ds§r
Summary: Show rainbow effect on sky
'''

[[subpack]]
define = "ALWAYS_REFLECTION"
materials = ["RenderChunk"]
description = '''
§eAlways Reflection§r
Summary: Enable aurora and ground reflection effect
'''

[[subpack]]
define = "MULTILAYER_CLOUDS"
materials = ["Clouds"]
description = '''
§9Multilayer Clouds§r
Summary: Add more clouds layer
'''

[[subpack]]
define = "SIMPLE_CLOUDS"
materials = ["Clouds"]
description = '''
§3Simple Clouds§r
Summary: Change to Simple Clouds
'''

[[subpack]]
define = "VANILLA_CLOUDS"
materials = ["Clouds"]
description = '''
§6Vanilla Clouds§r
Summary: Change to Vanilla style Clouds
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
§aNo Wave§r
Summary: No wave effect
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
Summary: Rounded clouds, wave effect and aurora at night
'''
